---
# tasks file for roles/frontend

- name: Install nginx
  apt: 
    name: "{{ package_name }}"
    state: present
    update_cache: yes 

# - name: Copy Html file
#   copy:
#     src: index.html # search index.html here
#     dest: /var/www/html/index.html
#   notify: restart nginx

- name: Copy Html Template
  template:
    src: index.html.j2 # search inside templates folder
    dest: /var/www/html/index.html
  notify: restart nginx