apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
    - name: mypod
      image: busybox
      command: ["sleep","3600"]
      volumeMounts:
        - name: config-volume
          mountPath: "/etc/config"
          readOnly: true
  
  volumes:
  - name: config-volume
    configMap:
      name: app-config


# kubectl apply -f demo-pod.yml
# kubectl get pods
# kubectl describe pod my-pod
# kubecttl exec -it my-pod -- sh
# cd /etc/config 
# ls
# cat APP_COLOR
# cat APP_MODE