web1 ansible_host=ec2-54-198-125-83.compute-1.amazonaws.com
web2 ansible_host=ec2-54-198-125-83.compute-1.amazonaws.com

[aws]
web1
web2

[aws:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/sonamkey.pem

; if you want to give alias name like web1 then ansible_host required
; for just dns or ip you can give it directly