apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx # use this label while connect with service
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
