apiVersion: v1
kind: Pod
metadata:
  name: secret-demo-pod
spec:
  containers:
  - name: busybox-contrainer
    image: busybox
    command: ["sleep","3600"]
    env:
    - name: DB_USER
      valueFrom:
        secretKeyRef:
          name: db-secret
          key: DB_USER
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: db-secret
          key: DB_PASSWORD

#  kubectl apply -f secret.yml
#  kubectl apply -f pod.yml
#  kubectl get pods
#  kubectl exec -it secret-demo-pod -- sh
# echo $DB_USER
# echo $DB_PASSWORD
# you can access credentials inside the pod as environment variable
# exit
# kubectl delete pod secret-demo-pod
# kubectl delete secret db-secret